import React from "react";
export const pokemonGen1 = [{pkdxnr:"1" ,name:"bisasam"}, {pkdxnr:"2" ,name:"bisaknosp"}, {pkdxnr:"3" ,name:"bisaflor"}, {pkdxnr:"4" ,name:"glumanda"}, {pkdxnr:"5" ,name:"glutexo"}, {pkdxnr:"6" ,name:"glurak"}, {pkdxnr:"7" ,name:"schiggy"}, {pkdxnr:"8" ,name:"schillok"}, {pkdxnr:"9" ,name:"turtok"}, {pkdxnr:"10" ,name:"raupy"}, {pkdxnr:"11" ,name:"safcon"}, {pkdxnr:"12" ,name:"smettbo"}, {pkdxnr:"13" ,name:"hornliu"}, {pkdxnr:"14" ,name:"kokuna"}, {pkdxnr:"15" ,name:"bibor"}, {pkdxnr:"16" ,name:"taubsi"}, {pkdxnr:"17" ,name:"tauboga"}, {pkdxnr:"18" ,name:"tauboss"}, {pkdxnr:"19" ,name:"rattfratz"}, {pkdxnr:"20" ,name:"rattikarl"}, {pkdxnr:"21" ,name:"habitak"}, {pkdxnr:"22" ,name:"ibitak"}, {pkdxnr:"23" ,name:"rettan"}, {pkdxnr:"24" ,name:"arbok"}, {pkdxnr:"25" ,name:"pikachu"}, {pkdxnr:"26" ,name:"raichu"}, {pkdxnr:"27" ,name:"sandan"}, {pkdxnr:"28" ,name:"sandamer"}, {pkdxnr:"29" ,name:"nidoran"}, {pkdxnr:"30" ,name:"nidorina"}, {pkdxnr:"31" ,name:"nidoqueen"}, {pkdxnr:"32" ,name:"nidoran"}, {pkdxnr:"33" ,name:"nidorino"}, {pkdxnr:"34" ,name:"nidoking"}, {pkdxnr:"35" ,name:"piepi"}, {pkdxnr:"36" ,name:"pixi"}, {pkdxnr:"37" ,name:"vulpix"}, {pkdxnr:"38" ,name:"vulnona"}, {pkdxnr:"39" ,name:"pummeluff"}, {pkdxnr:"40" ,name:"knuddeluff"}, {pkdxnr:"41" ,name:"zubat"}, {pkdxnr:"42" ,name:"golbat"}, {pkdxnr:"43" ,name:"myrapla"}, {pkdxnr:"44" ,name:"duflor"}, {pkdxnr:"45" ,name:"giflor"}, {pkdxnr:"46" ,name:"paras"}, {pkdxnr:"47" ,name:"parasek"}, {pkdxnr:"48" ,name:"bluzuk"}, {pkdxnr:"49" ,name:"omot"}, {pkdxnr:"50" ,name:"digda"}, {pkdxnr:"51" ,name:"digdri"}, {pkdxnr:"52" ,name:"mauzi"}, {pkdxnr:"53" ,name:"snobilikat"}, {pkdxnr:"54" ,name:"enton"}, {pkdxnr:"55" ,name:"entoron"}, {pkdxnr:"56" ,name:"menki"}, {pkdxnr:"57" ,name:"rasaff"}, {pkdxnr:"58" ,name:"fukano"}, {pkdxnr:"59" ,name:"arkani"}, {pkdxnr:"60" ,name:"quapsel"}, {pkdxnr:"61" ,name:"quaputzi"}, {pkdxnr:"62" ,name:"quappo"}, {pkdxnr:"63" ,name:"abra"}, {pkdxnr:"64" ,name:"kadabra"}, {pkdxnr:"65" ,name:"simsala"}, {pkdxnr:"66" ,name:"machollo"}, {pkdxnr:"67" ,name:"maschock"}, {pkdxnr:"68" ,name:"machomei"}, {pkdxnr:"69" ,name:"knofensa"}, {pkdxnr:"70" ,name:"ultrigaria"}, {pkdxnr:"71" ,name:"sarzenia"}, {pkdxnr:"72" ,name:"tentacha"}, {pkdxnr:"73" ,name:"tentoxa"}, {pkdxnr:"74" ,name:"kleinstein"}, {pkdxnr:"75" ,name:"georok"}, {pkdxnr:"76" ,name:"geowaz"}, {pkdxnr:"77" ,name:"ponita"}, {pkdxnr:"78" ,name:"gallopa"}, {pkdxnr:"79" ,name:"flegmon"}, {pkdxnr:"80" ,name:"lahmus"},
 {pkdxnr:"81" ,name:"magnetilo"}, {pkdxnr:"82" ,name:"magneton"}, {pkdxnr:"83" ,name:"porenta"}, {pkdxnr:"84" ,name:"dodu"}, {pkdxnr:"85" ,name:"dodri"}, {pkdxnr:"86" ,name:"jurob"}, {pkdxnr:"87" ,name:"jugong"}, {pkdxnr:"88" ,name:"sleima"}, {pkdxnr:"89" ,name:"sleimok"}, {pkdxnr:"90" ,name:"muschas"}, {pkdxnr:"91" ,name:"austos"}, {pkdxnr:"92" ,name:"nebulak"}, {pkdxnr:"93" ,name:"alpollo"}, {pkdxnr:"94" ,name:"gengar"}, {pkdxnr:"95" ,name:"onix"}, {pkdxnr:"96" ,name:"traumato"}, {pkdxnr:"97" ,name:"hypno"}, {pkdxnr:"98" ,name:"krabby"}, {pkdxnr:"99" ,name:"kingler"}, {pkdxnr:"100" ,name:"voltobal"}, {pkdxnr:"101" ,name:"lektrobal"}, {pkdxnr:"102" ,name:"owei"}, {pkdxnr:"103" ,name:"kokowei"}, {pkdxnr:"104" ,name:"tragosso"}, {pkdxnr:"105" ,name:"knogga"}, {pkdxnr:"106" ,name:"kicklee"}, {pkdxnr:"107" ,name:"nockchan"}, {pkdxnr:"108" ,name:"schlurp"}, {pkdxnr:"109" ,name:"smogon"}, {pkdxnr:"110" ,name:"smogmog"}, {pkdxnr:"111" ,name:"rihorn"}, {pkdxnr:"112" ,name:"rizeros"}, {pkdxnr:"113" ,name:"chaneira"}, {pkdxnr:"114" ,name:"tangela"}, {pkdxnr:"115" ,name:"kangama"}, {pkdxnr:"116" ,name:"seeper"}, {pkdxnr:"117" ,name:"seemon"}, {pkdxnr:"118" ,name:"goldini"}, {pkdxnr:"119" ,name:"golking"}, {pkdxnr:"120" ,name:"sterndu"}, {pkdxnr:"121" ,name:"starmie"}, {pkdxnr:"122" ,name:"pantimos"}, {pkdxnr:"123" ,name:"sichlor"}, {pkdxnr:"124" ,name:"rossana"}, {pkdxnr:"125" ,name:"elektek"}, {pkdxnr:"126" ,name:"magmar"}, {pkdxnr:"127" ,name:"pinsir"}, {pkdxnr:"128" ,name:"tauros"}, {pkdxnr:"129" ,name:"karpador"}, {pkdxnr:"130" ,name:"garados"}, {pkdxnr:"131" ,name:"lapras"}, {pkdxnr:"132" ,name:"ditto"}, {pkdxnr:"133" ,name:"evoli"}, {pkdxnr:"134" ,name:"aquana"}, {pkdxnr:"135" ,name:"blitza"}, {pkdxnr:"136" ,name:"flamara"}, {pkdxnr:"137" ,name:"porygon"}, {pkdxnr:"138" ,name:"amonitas"}, {pkdxnr:"139" ,name:"amoroso"}, {pkdxnr:"140" ,name:"kabuto"}, {pkdxnr:"141" ,name:"kabutops"}, {pkdxnr:"142" ,name:"aerodactyl"}, {pkdxnr:"143" ,name:"relaxo"}, {pkdxnr:"144" ,name:"arktos"}, {pkdxnr:"145" ,name:"zapdos"}, {pkdxnr:"146" ,name:"lavados"}, {pkdxnr:"147" ,name:"dratini"}, {pkdxnr:"148" ,name:"dragonir"}, {pkdxnr:"149" ,name:"dragoran"}, {pkdxnr:"150" ,name:"mewtu"}, {pkdxnr:"151" ,name:"mew"}]
export const pokemonGen2 = [{pkdxnr:"1" ,name:"endivie"}, {pkdxnr:"2" ,name:"lorblatt"}, {pkdxnr:"3" ,name:"meganie"}, {pkdxnr:"4" ,name:"feurigel"}, {pkdxnr:"5" ,name:"igelavar"}, {pkdxnr:"6" ,name:"tornupto"}, {pkdxnr:"7" ,name:"karnimani"}, {pkdxnr:"8" ,name:"tyracroc"}, {pkdxnr:"9" ,name:"impergator"}, {pkdxnr:"10" ,name:"wiesor"}, {pkdxnr:"11" ,name:"wiesenior"}, {pkdxnr:"12" ,name:"hoothoot"}, {pkdxnr:"13" ,name:"noctuh"}, {pkdxnr:"14" ,name:"ledyba"}, {pkdxnr:"15" ,name:"ledian"}, {pkdxnr:"16" ,name:"webarak"}, {pkdxnr:"17" ,name:"ariados"}, {pkdxnr:"18" ,name:"iksbat"}, {pkdxnr:"19" ,name:"lampi"}, {pkdxnr:"20" ,name:"lanturn"}, {pkdxnr:"21" ,name:"pichu"}, {pkdxnr:"22" ,name:"pii"}, {pkdxnr:"23" ,name:"fluffeluff"}, {pkdxnr:"24" ,name:"togepi"}, {pkdxnr:"25" ,name:"togetic"}, {pkdxnr:"26" ,name:"natu"}, {pkdxnr:"27" ,name:"xatu"}, {pkdxnr:"28" ,name:"voltilamm"}, {pkdxnr:"29" ,name:"waaty"}, {pkdxnr:"30" ,name:"ampharos"}, {pkdxnr:"31" ,name:"blubella"}, {pkdxnr:"32" ,name:"marill"}, {pkdxnr:"33" ,name:"azumarill"}, {pkdxnr:"34" ,name:"mogelbaum"}, {pkdxnr:"35" ,name:"quaxo"}, {pkdxnr:"36" ,name:"hoppspross"}, {pkdxnr:"37" ,name:"hubelupf"}, {pkdxnr:"38" ,name:"papungha"}, {pkdxnr:"39" ,name:"griffel"}, {pkdxnr:"40" ,name:"sonnkern"}, {pkdxnr:"41" ,name:"sonnflora"}, {pkdxnr:"42" ,name:"yanma"}, {pkdxnr:"43" ,name:"felino"}, {pkdxnr:"44" ,name:"morlord"}, {pkdxnr:"45" ,name:"psiana"}, {pkdxnr:"46" ,name:"nachtara"}, {pkdxnr:"47" ,name:"kramurx"}, {pkdxnr:"48" ,name:"laschoking"}, {pkdxnr:"49" ,name:"traunfugil"}, {pkdxnr:"50" ,name:"icognito"}, {pkdxnr:"51" ,name:"woingenau"}, {pkdxnr:"52" ,name:"girafarig"}, {pkdxnr:"53" ,name:"tannza"}, {pkdxnr:"54" ,name:"forstellka"}, {pkdxnr:"55" ,name:"dummisel"}, {pkdxnr:"56" ,name:"skorgla"}, {pkdxnr:"57" ,name:"stahlos"},
{pkdxnr:"58" ,name:"snubbull"}, {pkdxnr:"59" ,name:"granbull"}, {pkdxnr:"60" ,name:"baldorfish"}, {pkdxnr:"61" ,name:"scherox"}, {pkdxnr:"62" ,name:"pottrott"}, {pkdxnr:"63" ,name:"skaraborn"}, {pkdxnr:"64" ,name:"sniebel"}, {pkdxnr:"65" ,name:"teddiursa"}, {pkdxnr:"66" ,name:"ursaring"}, {pkdxnr:"67" ,name:"schneckmag"}, {pkdxnr:"68" ,name:"magcargo"}, {pkdxnr:"69" ,name:"quiekel"}, {pkdxnr:"70" ,name:"keifel"}, {pkdxnr:"71" ,name:"corasonn"}, {pkdxnr:"72" ,name:"remoraid"}, {pkdxnr:"73" ,name:"octillery"}, {pkdxnr:"74" ,name:"botogel"}, {pkdxnr:"75" ,name:"mantax"}, {pkdxnr:"76" ,name:"panzaeron"}, {pkdxnr:"77" ,name:"hunduster"}, {pkdxnr:"78" ,name:"hundemon"}, {pkdxnr:"79" ,name:"seedraking"}, {pkdxnr:"80" ,name:"phanpy"}, {pkdxnr:"81" ,name:"donphan"}, {pkdxnr:"82" ,name:"porygon-"}, {pkdxnr:"83" ,name:"damhirplex"}, {pkdxnr:"84" ,name:"farbeagle"}, {pkdxnr:"85" ,name:"rabauz"}, {pkdxnr:"86" ,name:"kapoera"}, {pkdxnr:"87" ,name:"kussilla"}, {pkdxnr:"88" ,name:"elekid"}, {pkdxnr:"89" ,name:"magby"}, {pkdxnr:"90" ,name:"miltank"}, {pkdxnr:"91" ,name:"heiteira"}, {pkdxnr:"92" ,name:"raikou"}, {pkdxnr:"93" ,name:"entei"}, {pkdxnr:"94" ,name:"suicune"}, {pkdxnr:"95" ,name:"larvitar"}, {pkdxnr:"96" ,name:"pupitar"}, {pkdxnr:"97" ,name:"despotar"}, {pkdxnr:"98" ,name:"lugia"}, {pkdxnr:"99" ,name:"ho-oh"}, {pkdxnr:"100" ,name:"celebi"}];
export const pokemonGen3 = [{pkdxnr:"1" ,name:"geckarbor"}, {pkdxnr:"2" ,name:"reptain"}, {pkdxnr:"3" ,name:"gewaldro"}, {pkdxnr:"4" ,name:"flemmli"}, {pkdxnr:"5" ,name:"jungglut"}, {pkdxnr:"6" ,name:"lohgock"}, {pkdxnr:"7" ,name:"hydropi"}, {pkdxnr:"8" ,name:"moorabbel"}, {pkdxnr:"9" ,name:"sumpex"}, {pkdxnr:"10" ,name:"fiffyen"}, {pkdxnr:"11" ,name:"magnayen"}, {pkdxnr:"12" ,name:"zigzachs"}, {pkdxnr:"13" ,name:"geradaks"}, {pkdxnr:"14" ,name:"waumpel"}, {pkdxnr:"15" ,name:"schaloko"}, {pkdxnr:"16" ,name:"papinella"}, {pkdxnr:"17" ,name:"panekon"}, {pkdxnr:"18" ,name:"pudox"}, {pkdxnr:"19" ,name:"loturzel"}, {pkdxnr:"20" ,name:"lombrero"}, {pkdxnr:"21" ,name:"kappalores"}, {pkdxnr:"22" ,name:"samurzel"}, {pkdxnr:"23" ,name:"blanas"}, {pkdxnr:"24" ,name:"tengulist"}, {pkdxnr:"25" ,name:"schwalbini"}, {pkdxnr:"26" ,name:"schwalboss"}, {pkdxnr:"27" ,name:"wingull"}, {pkdxnr:"28" ,name:"pelipper"}, {pkdxnr:"29" ,name:"trasla"}, {pkdxnr:"30" ,name:"kirlia"}, {pkdxnr:"31" ,name:"guardevoir"}, {pkdxnr:"32" ,name:"geweiher"}, {pkdxnr:"33" ,name:"maskeregen"}, {pkdxnr:"34" ,name:"knilz"}, {pkdxnr:"35" ,name:"kapilz"}, {pkdxnr:"36" ,name:"bummelz"}, {pkdxnr:"37" ,name:"muntier"}, {pkdxnr:"38" ,name:"letarking"}, {pkdxnr:"39" ,name:"nincada"}, {pkdxnr:"40" ,name:"ninjask"}, {pkdxnr:"41" ,name:"ninjatom"}, {pkdxnr:"42" ,name:"flurmel"}, {pkdxnr:"43" ,name:"krakeelo"}, {pkdxnr:"44" ,name:"krawumms"}, {pkdxnr:"45" ,name:"makuhita"}, {pkdxnr:"46" ,name:"hariyama"}, {pkdxnr:"47" ,name:"azurill"}, {pkdxnr:"48" ,name:"nasgnet"}, {pkdxnr:"49" ,name:"eneco"}, {pkdxnr:"50" ,name:"enekoro"}, {pkdxnr:"51" ,name:"zobiris"}, {pkdxnr:"52" ,name:"flunkifer"}, {pkdxnr:"53" ,name:"stollunior"}, {pkdxnr:"54" ,name:"stollrak"}, {pkdxnr:"55" ,name:"stolloss"}, {pkdxnr:"56" ,name:"meditie"}, {pkdxnr:"57" ,name:"meditalis"}, {pkdxnr:"58" ,name:"frizelbliz"}, {pkdxnr:"59" ,name:"voltenso"}, {pkdxnr:"60" ,name:"plusle"}, {pkdxnr:"61" ,name:"minun"}, {pkdxnr:"62" ,name:"volbeat"}, {pkdxnr:"63" ,name:"illumise"}, {pkdxnr:"64" ,name:"roselia"}, {pkdxnr:"65" ,name:"schluppuck"},
{pkdxnr:"66" ,name:"schlukwech"}, {pkdxnr:"67" ,name:"kanivanha"}, {pkdxnr:"68" ,name:"tohaido"}, {pkdxnr:"69" ,name:"wailmer"}, {pkdxnr:"70" ,name:"wailord"}, {pkdxnr:"71" ,name:"camaub"}, {pkdxnr:"72" ,name:"camerupt"}, {pkdxnr:"73" ,name:"qurtel"}, {pkdxnr:"74" ,name:"spoink"}, {pkdxnr:"75" ,name:"groink"}, {pkdxnr:"76" ,name:"pandir"}, {pkdxnr:"77" ,name:"knacklion"}, {pkdxnr:"78" ,name:"vibrava"}, {pkdxnr:"79" ,name:"libelldra"}, {pkdxnr:"80" ,name:"tuska"}, {pkdxnr:"81" ,name:"noktuska"}, {pkdxnr:"82" ,name:"wablu"}, {pkdxnr:"83" ,name:"altaria"}, {pkdxnr:"84" ,name:"sengo"}, {pkdxnr:"85" ,name:"vipitis"}, {pkdxnr:"86" ,name:"lunastein"}, {pkdxnr:"87" ,name:"sonnfel"}, {pkdxnr:"88" ,name:"schmerbe"}, {pkdxnr:"89" ,name:"welsar"}, {pkdxnr:"90" ,name:"krebscorps"}, {pkdxnr:"91" ,name:"krebutack"}, {pkdxnr:"92" ,name:"puppance"}, {pkdxnr:"93" ,name:"lepumentas"}, {pkdxnr:"94" ,name:"liliep"}, {pkdxnr:"95" ,name:"wielie"}, {pkdxnr:"96" ,name:"anorith"}, {pkdxnr:"97" ,name:"armaldo"}, {pkdxnr:"98" ,name:"barschwa"}, {pkdxnr:"99" ,name:"milotic"}, {pkdxnr:"100" ,name:"formeo"}, {pkdxnr:"101" ,name:"kecleon"}, {pkdxnr:"102" ,name:"shuppet"}, {pkdxnr:"103" ,name:"banette"}, {pkdxnr:"104" ,name:"zwirrlicht"}, {pkdxnr:"105" ,name:"zwirrklop"}, {pkdxnr:"106" ,name:"tropius"}, {pkdxnr:"107" ,name:"palimpalim"}, {pkdxnr:"108" ,name:"absol"}, {pkdxnr:"109" ,name:"isso"}, {pkdxnr:"110" ,name:"schneppke"}, {pkdxnr:"111" ,name:"firnontor"}, {pkdxnr:"112" ,name:"seemops"}, {pkdxnr:"113" ,name:"seejong"}, {pkdxnr:"114" ,name:"walraisa"}, {pkdxnr:"115" ,name:"perlu"}, {pkdxnr:"116" ,name:"aalabyss"}, {pkdxnr:"117" ,name:"saganabyss"}, {pkdxnr:"118" ,name:"relicanth"}, {pkdxnr:"119" ,name:"liebiskus"}, {pkdxnr:"120" ,name:"kindwurm"}, {pkdxnr:"121" ,name:"draschel"}, {pkdxnr:"122" ,name:"brutalanda"}, {pkdxnr:"123" ,name:"tanhel"}, {pkdxnr:"124" ,name:"metang"}, {pkdxnr:"125" ,name:"metagross"}, {pkdxnr:"126" ,name:"regirock"}, {pkdxnr:"127" ,name:"regice"}, {pkdxnr:"128" ,name:"registeel"}, {pkdxnr:"129" ,name:"latias"}, {pkdxnr:"130" ,name:"latios"}, {pkdxnr:"131" ,name:"kyogre"}, {pkdxnr:"132" ,name:"groudon"}, {pkdxnr:"133" ,name:"rayquaza"}, {pkdxnr:"134" ,name:"jirachi"}, {pkdxnr:"135" ,name:"deoxys"}];
export const pokemonGen4 = [{pkdxnr:"1" ,name:"chelast"}, {pkdxnr:"2" ,name:"chelcarain"}, {pkdxnr:"3" ,name:"chelterrar"}, {pkdxnr:"4" ,name:"panflam"}, {pkdxnr:"5" ,name:"panpyro"}, {pkdxnr:"6" ,name:"panferno"}, {pkdxnr:"7" ,name:"plinfa"}, {pkdxnr:"8" ,name:"pliprin"}, {pkdxnr:"9" ,name:"impoleon"}, {pkdxnr:"10" ,name:"staralili"}, {pkdxnr:"11" ,name:"staravia"}, {pkdxnr:"12" ,name:"staraptor"}, {pkdxnr:"13" ,name:"bidiza"}, {pkdxnr:"14" ,name:"bidifas"}, {pkdxnr:"15" ,name:"zirpurze"}, {pkdxnr:"16" ,name:"zirpeise"}, {pkdxnr:"17" ,name:"sheinux"}, {pkdxnr:"18" ,name:"luxio"}, {pkdxnr:"19" ,name:"luxtra"}, {pkdxnr:"20" ,name:"knospi"}, {pkdxnr:"21" ,name:"roserade"}, {pkdxnr:"22" ,name:"koknodon"}, {pkdxnr:"23" ,name:"rameidon"}, {pkdxnr:"24" ,name:"schilterus"}, {pkdxnr:"25" ,name:"bollterus"}, {pkdxnr:"26" ,name:"burmy"}, {pkdxnr:"27" ,name:"burmadame"}, {pkdxnr:"28" ,name:"moterpel"}, {pkdxnr:"29" ,name:"wadribie"}, {pkdxnr:"30" ,name:"honweisel"}, {pkdxnr:"31" ,name:"pachirisu"}, {pkdxnr:"32" ,name:"bamelin"}, {pkdxnr:"33" ,name:"bojelin"}, {pkdxnr:"34" ,name:"kikugi"}, {pkdxnr:"35" ,name:"kinoso"}, {pkdxnr:"36" ,name:"schalellos"}, {pkdxnr:"37" ,name:"gastrodon"}, {pkdxnr:"38" ,name:"ambidiffel"}, {pkdxnr:"39" ,name:"driftlon"}, {pkdxnr:"40" ,name:"drifzepeli"}, {pkdxnr:"41" ,name:"haspiror"}, {pkdxnr:"42" ,name:"schlapor"}, {pkdxnr:"43" ,name:"traunmagil"}, {pkdxnr:"44" ,name:"kramshef"}, {pkdxnr:"45" ,name:"charmian"}, {pkdxnr:"46" ,name:"shnurgarst"}, {pkdxnr:"47" ,name:"klingplim"}, {pkdxnr:"48" ,name:"skunkapuh"}, {pkdxnr:"49" ,name:"skuntank"}, {pkdxnr:"50" ,name:"bronzel"}, {pkdxnr:"51" ,name:"bronzong"}, {pkdxnr:"52" ,name:"mobai"}, {pkdxnr:"53" ,name:"pantimimi"}, {pkdxnr:"54" ,name:"wonneira"}, {pkdxnr:"55" ,name:"plaudagei"}, {pkdxnr:"56" ,name:"kryppuk"}, {pkdxnr:"57" ,name:"kaumalat"}, {pkdxnr:"58" ,name:"knarksel"}, {pkdxnr:"59" ,name:"knakrack"}, {pkdxnr:"60" ,name:"mampfaxo"},
{pkdxnr:"61" ,name:"riolu"}, {pkdxnr:"62" ,name:"lucario"}, {pkdxnr:"63" ,name:"hippopotas"}, {pkdxnr:"64" ,name:"hippoterus"}, {pkdxnr:"65" ,name:"pionskora"}, {pkdxnr:"66" ,name:"piondragi"}, {pkdxnr:"67" ,name:"glibunkel"}, {pkdxnr:"68" ,name:"toxiquak"}, {pkdxnr:"69" ,name:"venuflibis"}, {pkdxnr:"70" ,name:"finneon"}, {pkdxnr:"71" ,name:"lumineon"}, {pkdxnr:"72" ,name:"mantirps"}, {pkdxnr:"73" ,name:"shnebedeck"}, {pkdxnr:"74" ,name:"rexblisar"}, {pkdxnr:"75" ,name:"snibunna"}, {pkdxnr:"76" ,name:"magnezone"}, {pkdxnr:"77" ,name:"schlurplek"}, {pkdxnr:"78" ,name:"rihornior"}, {pkdxnr:"79" ,name:"tangoloss"}, {pkdxnr:"80" ,name:"elevoltek"}, {pkdxnr:"81" ,name:"magbrant"}, {pkdxnr:"82" ,name:"togekiss"}, {pkdxnr:"83" ,name:"yanmega"}, {pkdxnr:"84" ,name:"folipurba"}, {pkdxnr:"85" ,name:"glaziola"}, {pkdxnr:"86" ,name:"skorgro"}, {pkdxnr:"87" ,name:"mamutel"}, {pkdxnr:"88" ,name:"porygon-z"}, {pkdxnr:"89" ,name:"galagladi"}, {pkdxnr:"90" ,name:"voluminas"}, {pkdxnr:"91" ,name:"zwirrfinst"}, {pkdxnr:"92" ,name:"frosdedje"}, {pkdxnr:"93" ,name:"rotom"}, {pkdxnr:"94" ,name:"selfe"}, {pkdxnr:"95" ,name:"vesprit"}, {pkdxnr:"96" ,name:"tobutz"}, {pkdxnr:"97" ,name:"dialga"}, {pkdxnr:"98" ,name:"palkia"}, {pkdxnr:"99" ,name:"heatran"}, {pkdxnr:"100" ,name:"regigigas"}, {pkdxnr:"101" ,name:"giratina"}, {pkdxnr:"102" ,name:"cresselia"}, {pkdxnr:"103" ,name:"phione"}, {pkdxnr:"104" ,name:"manaphy"}, {pkdxnr:"105" ,name:"darkrai"}, {pkdxnr:"106" ,name:"shaymin"}, {pkdxnr:"107" ,name:"arceus"}];


const Table = (props) => {
  const resultsRender = [];
  let pokemonArray = [];
  switch (props.selectedGeneration) {
    case 1:
      pokemonArray = pokemonGen1
      break;
    case 2:
      pokemonArray = pokemonGen2
      break;
    case 3:
      pokemonArray = pokemonGen3
      break;
    case 4:
      pokemonArray = pokemonGen4
      break;
    default:
      pokemonArray = pokemonGen1
      break;
  }

  for (var i = 0; i < pokemonArray.length; i += 3) {
    resultsRender.push(
      <tr key={pokemonArray[i].pkdxnr}>
      {
        pokemonArray.slice(i, i + 3)
          .map(pokemon => <td key={pokemon.pkdxnr}><b>{pokemon.pkdxnr}:</b><i id={pokemon.pkdxnr} hidden={true}> {capitalizeFirstLetter(pokemon.name)}</i></td>)
      }
      </tr>
    );
  }

return (
  <table border={1}><tbody>{resultsRender}</tbody></table>    
);
  }


  function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }

export default Table